# Generated by Django 4.2.3 on 2023-08-03 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_projectdetail_delete_todolistitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectdetail',
            name='id',
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='roll_no',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
