# Generated by Django 4.2.3 on 2023-08-04 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_projectdetail_g_no_alter_projectdetail_roll_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdetail',
            name='g_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='roll_no',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
